// <auto-generated />
using System;
using ExpectativasDeMercado.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpectativasDeMercado.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    partial class MarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MarketExpectation", b =>
                {
                    b.Property<string>("Indicador")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("BaseCalculo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DesvioPadrao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Maximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Media")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mediana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Minimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroRespondentes")
                        .HasColumnType("int");

                    b.HasKey("Indicador", "Data");

                    b.ToTable("MarketExpectations");
                });

            modelBuilder.Entity("SelicExpectation", b =>
                {
                    b.Property<string>("Indicador")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BaseCalculo")
                        .HasColumnType("int");

                    b.Property<double>("DesvioPadrao")
                        .HasColumnType("float");

                    b.Property<double>("Maximo")
                        .HasColumnType("float");

                    b.Property<double>("Media")
                        .HasColumnType("float");

                    b.Property<double>("Mediana")
                        .HasColumnType("float");

                    b.Property<double>("Minimo")
                        .HasColumnType("float");

                    b.Property<int>("NumeroRespondentes")
                        .HasColumnType("int");

                    b.Property<string>("Reuniao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Indicador", "Data");

                    b.ToTable("SelicExpectations");
                });
#pragma warning restore 612, 618
        }
    }
}
